### ISSUE TITLE
Kosumoth LUA error

### ISSUE THREAD

**Issue by NLZ** [cheald/WorldQuestAssistant#2]
Trying to create a Kosumoth group gives this error whatevery I try:

`5x WorldQuestAssistant\core.lua:386: Usage: C_LFGList.CreateListing(lfgID, "groupName", itemLevel, honorLevel, "voiceChat", "comment", autoAccept, privateGroup[, questID])
[C]: in function `CreateListing'
WorldQuestAssistant\core.lua:386: in function `CreateQuestGroup'
WorldQuestAssistant\ui.lua:34: in function `OnAccept'
FrameXML\StaticPopup.lua:4393: in function `StaticPopup_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals:
(*temporary) = nil
(*temporary) = ""
(*temporary) = 0
(*temporary) = 0
(*temporary) = ""
(*temporary) = "Created by World Quest Assistant #WQ:43798#PVP#"
(*temporary) = true
(*temporary) = false
(*temporary) = 43798`

**Comment by saibantes** [comment]
Note to self (or whoever will fix this):
LFGListUtil_GetQuestCategoryData() returns nil for Kosumoth.

Maybe fix this together with: Some world bosses groups are limited to 5 people, because the AcitivityID corresponds to Groups:WorldQuests (CategoryID 1) instead of Raids:WorldBosses (CategoryID 3).

**Comment by saibantes** [comment]
Fixed it ... by disabling Kosumoth groups in WQA entirely. Sorry about that.
Will re-consider it when more similar dysfunctional WQs pop up.
